# Generated by Django 4.0.3 on 2022-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('real_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('medium_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('gray_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
